### ISSUE TITLE
setup an api for crud operation and paste the url here

### ISSUE THREAD

**Issue by mariyareshma** [mariyareshma/crud_api_app#3]

**Comment by mariyareshma** [comment]
//get all users
method=get
https://crudcrud.com/api/ecb6f60715ac4cd5b7a8bde16cb50b73/users

//edit user
method=put
https://crudcrud.com/api/ecb6f60715ac4cd5b7a8bde16cb50b73/users/63f325371d8b0e03e8141339


{
  "Name":"mariya",
  "age":40
}


//delete user

method=delete
https://crudcrud.com/api/ecb6f60715ac4cd5b7a8bde16cb50b73/users/63f322691d8b0e03e8141325

//post user
method=post

https://crudcrud.com/api/ecb6f60715ac4cd5b7a8bde16cb50b73/users

**Comment by rajkumar82** [comment]
ok task is completed
